apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapps
  namespace: argocd
spec:
  project: produzione
  source:
    chart: kubeapps
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.7.2
    #helm:
    #  releaseName: kubernetes-dashboard
    #  values: |
    #    ingress:
    #      enabled: false
    #    kong:
    #      enabled: false
    #    nginx:
    #      enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeapps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
