apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapps
  namespace: argocd
spec:
  project: produzione
  source:
    chart: kubeapps
    repoURL: registry-1.docker.io/bitnamicharts/kubeapps
    targetRevision: 14.7.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeapps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
